# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Somerville YIMBY
email: steering@somervilleyimby.org
description: >- # this means to ignore newlines until "baseurl:"
  A group of Somerville residents advocating for smart growth that benefits everyone.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://somervilleyimby.org # the base hostname & protocol for your site, e.g. http://example.com
locale: en-us
logo: /img/logo@3x.png

twitter:
  username: SomervilleYIMBY
  card: summary

social:
  links:
    - https://twitter.com/SomervilleYIMBY
    - https://www.facebook.com/SomervilleYIMBY
    - https://github.com/somervilleyimby
    - https://better.boston/@somervilleyimby
    - https://bsky.app/profile/somervilleyimby.org
    - https://www.threads.net/@somervilleyimby

footer_links:
  - title: Twitter
    url: https://twitter.com/SomervilleYIMBY
    icon: fab fa-brands fa-square-twitter
  - title: Facebook
    url: https://www.facebook.com/SomervilleYIMBY
    icon: fab fa-brands fa-square-facebook
  - title: Feed
    url: /feed.xml
    icon: fas fa-rss-square

footer_scripts:
  - https://code.jquery.com/jquery-3.7.0.min.js
  - /assets/js/main.min.js
  - https://kit.fontawesome.com/a693adcc79.js

google_analytics: UA-96931256-1

copyright: © 2017–2021 Somerville YIMBY

permalink: pretty

# Build settings
remote_theme: mmistakes/so-simple-theme@7c881be
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
